name: Rust CI

on:
  push:
    branches: [ main, rust_migration ]
  pull_request:
    branches: [ main, rust_migration ]

jobs:
  check:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check Formatting
        run: cargo fmt --check

      - name: Clippy Linter
        run: cargo clippy -- -D warnings

      - name: Run Tests
        run: cargo test --all-targets
